import { useState } from 'react';

/**
 * ComparePanel — shown when user searches "X vs Y"
 * Displays a side-by-side comparison table generated by AI.
 * Google just shows links. We give an actual answer.
 *
 * Props:
 *   comparison: {
 *     item_a: string,
 *     item_b: string,
 *     verdict: string,         // 1-2 sentence summary of winner
 *     winner: 'a' | 'b' | 'tie',
 *     rows: [
 *       { category: string, a: string, b: string, winner: 'a' | 'b' | 'tie' }
 *     ]
 *   }
 */
export default function ComparePanel({ comparison }) {
  const [expanded, setExpanded] = useState(true);

  if (!comparison || !comparison.rows || comparison.rows.length === 0) return null;

  const { item_a, item_b, verdict, winner, rows } = comparison;

  const winnerLabel =
    winner === 'a' ? item_a :
    winner === 'b' ? item_b :
    'Tie';

  const winnerColor =
    winner === 'a' ? 'text-green-600 dark:text-green-400' :
    winner === 'b' ? 'text-blue-600 dark:text-blue-400' :
    'text-gray-600 dark:text-gray-400';

  return (
    <div className="mb-6 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-2xl overflow-hidden shadow-sm">

      {/* ── Header ── */}
      <div className="bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-950 dark:to-purple-950 px-5 py-4 border-b border-gray-200 dark:border-gray-700">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            {/* Compare icon */}
            <div className="w-7 h-7 bg-indigo-600 rounded-lg flex items-center justify-center flex-shrink-0">
              <svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round"
                  d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
              </svg>
            </div>
            <div>
              <span className="text-indigo-700 dark:text-indigo-300 font-semibold text-sm">
                AI Comparison
              </span>
              <span className="ml-2 text-xs px-2 py-0.5 bg-indigo-100 dark:bg-indigo-900 text-indigo-600 dark:text-indigo-300 rounded-full">
                Not available on Google
              </span>
            </div>
          </div>
          {/* Collapse toggle */}
          <button
            onClick={() => setExpanded((v) => !v)}
            className="p-1 rounded-lg hover:bg-indigo-100 dark:hover:bg-indigo-900 text-indigo-500 transition-colors"
            aria-label={expanded ? 'Collapse' : 'Expand'}
          >
            <svg className={`w-4 h-4 transition-transform ${expanded ? '' : 'rotate-180'}`}
              fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 15l7-7 7 7" />
            </svg>
          </button>
        </div>

        {/* Title row with item names */}
        <div className="mt-3 flex items-center gap-3">
          <span className="font-bold text-gray-800 dark:text-gray-100 text-lg">{item_a}</span>
          <span className="text-gray-400 font-medium text-sm px-2 py-0.5 bg-white dark:bg-gray-700 rounded-full border border-gray-200 dark:border-gray-600">
            vs
          </span>
          <span className="font-bold text-gray-800 dark:text-gray-100 text-lg">{item_b}</span>
        </div>
      </div>

      {expanded && (
        <>
          {/* ── Comparison table ── */}
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 dark:bg-gray-750 border-b border-gray-200 dark:border-gray-700">
                  <th className="text-left px-5 py-3 text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wide w-1/4">
                    Category
                  </th>
                  {/* Item A header */}
                  <th className="text-left px-5 py-3 w-[37.5%]">
                    <span className={`font-semibold ${winner === 'a' ? 'text-green-600 dark:text-green-400' : 'text-gray-700 dark:text-gray-300'}`}>
                      {item_a}
                      {winner === 'a' && (
                        <span className="ml-2 text-xs bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300 px-1.5 py-0.5 rounded-full">
                          Winner
                        </span>
                      )}
                    </span>
                  </th>
                  {/* Item B header */}
                  <th className="text-left px-5 py-3 w-[37.5%]">
                    <span className={`font-semibold ${winner === 'b' ? 'text-blue-600 dark:text-blue-400' : 'text-gray-700 dark:text-gray-300'}`}>
                      {item_b}
                      {winner === 'b' && (
                        <span className="ml-2 text-xs bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 px-1.5 py-0.5 rounded-full">
                          Winner
                        </span>
                      )}
                    </span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row, i) => (
                  <tr
                    key={i}
                    className={`border-b border-gray-100 dark:border-gray-700 last:border-0 ${
                      i % 2 === 0 ? 'bg-white dark:bg-gray-800' : 'bg-gray-50 dark:bg-gray-750'
                    }`}
                  >
                    {/* Category */}
                    <td className="px-5 py-3 font-medium text-gray-600 dark:text-gray-400 text-xs uppercase tracking-wide align-top">
                      {row.category}
                    </td>

                    {/* Item A value */}
                    <td className={`px-5 py-3 text-gray-700 dark:text-gray-300 align-top leading-relaxed ${
                      row.winner === 'a' ? 'bg-green-50 dark:bg-green-950' : ''
                    }`}>
                      <div className="flex items-start gap-2">
                        {row.winner === 'a' && (
                          <svg className="w-4 h-4 text-green-500 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                          </svg>
                        )}
                        <span>{row.a}</span>
                      </div>
                    </td>

                    {/* Item B value */}
                    <td className={`px-5 py-3 text-gray-700 dark:text-gray-300 align-top leading-relaxed ${
                      row.winner === 'b' ? 'bg-blue-50 dark:bg-blue-950' : ''
                    }`}>
                      <div className="flex items-start gap-2">
                        {row.winner === 'b' && (
                          <svg className="w-4 h-4 text-blue-500 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                          </svg>
                        )}
                        <span>{row.b}</span>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* ── Verdict bar ── */}
          {verdict && (
            <div className="px-5 py-4 bg-gradient-to-r from-indigo-50 to-purple-50 dark:from-indigo-950 dark:to-purple-950 border-t border-gray-200 dark:border-gray-700">
              <div className="flex items-start gap-3">
                <div className="flex-shrink-0 mt-0.5">
                  <svg className="w-5 h-5 text-indigo-500" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                  </svg>
                </div>
                <div>
                  <span className="text-xs font-semibold text-indigo-600 dark:text-indigo-400 uppercase tracking-wide">
                    AI Verdict —{' '}
                    <span className={winnerColor}>
                      {winner === 'tie' ? 'It\'s a tie' : `${winnerLabel} wins`}
                    </span>
                  </span>
                  <p className="text-sm text-gray-700 dark:text-gray-300 mt-1 leading-relaxed">
                    {verdict}
                  </p>
                </div>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}